# Mac Symbols

name: mac-symbols
parent: default

matches:
  - triggers: [":command", ":cmd"]
    replace: "⌘"
  - trigger: :shift
    replace: "⇧"
  - triggers: [":control", ":ctrl"]
    replace: "⌃"
  - triggers: [":option", ":alt"]
    replace: "⌥"
  - trigger: :left
    replace: "←"
  - trigger: :right
    replace: "→"
  - trigger: :up
    replace: "↑"
  - trigger: :down
    replace: "↓"
  - triggers: [":capslock", ":caps_lock"]
    replace: "⇪"
  - trigger: :escape
    replace: "⎋"
  - trigger: :eject
    replace: "⏏"
  - trigger: :return
    replace: "↵"
  - trigger: :enter
    replace: "⌅"
  - trigger: :tab
    replace: "⇥"
  - triggers: [":backtab", ":bktab"]
    replace: "⇤"
  - triggers: [":pageup", ":pgup"]
    replace: "⇞"
  - triggers: [":pagedown", ":pgdown", ":pgdwn"]
    replace: "⇟"
  - trigger: :home
    replace: "↖"
  - trigger: :end
    replace: "↘"
  - trigger: :space
    replace: "␣"
  - trigger: :delete
    replace: "⌫"
  - triggers: [":reversedelete", ":rdelete", ":forwarddelete", ":fdelete" ":backspace", ":bkspc"]
    replace: "⌦"
